package graft

import (
	"reflect"
	"sort"
	"testing"
)

// Every expected order below was generated by running the live spruce
// binary (v1.35.16) over a fixture map holding the same keys: quoted keys
// for string-class rows, bare keys for numeric-tier rows. Rows marked
// "residual" assert graft's chosen target order where spruce's
// quoted-string tier makes exact parity unreachable (see
// docs/spruce/known-gaps.md, mixed-key-type-map-encoding-order).
func TestSpruceKeyLessOrdering(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want []string
	}{
		{
			name: "letters sort by raw rune, uppercase first",
			in:   []string{"zulu", "alpha", "Mike"},
			want: []string{"Mike", "alpha", "zulu"},
		},
		{
			name: "case pair",
			in:   []string{"ax", "Zx"},
			want: []string{"Zx", "ax"},
		},
		{
			name: "integer-only keys sort numerically",
			in:   []string{"443", "8080", "80"},
			want: []string{"80", "443", "8080"},
		},
		{
			name: "pure digit strings sort numerically",
			in:   []string{"10", "2", "9"},
			want: []string{"2", "9", "10"},
		},
		{
			name: "digit runs and digit-before-letter",
			in:   []string{"10x", "b2", "alpha", "1a", "a1", "2x"},
			want: []string{"1a", "2x", "10x", "a1", "alpha", "b2"},
		},
		{
			name: "non-letters sort before letters by raw rune",
			in:   []string{"ax", "~t", "_x", "|p", "Zx"},
			want: []string{"_x", "|p", "~t", "Zx", "ax"},
		},
		{
			name: "empty digit run counts as zero",
			in:   []string{"int64_val", "int_val"},
			want: []string{"int_val", "int64_val"},
		},
		{
			name: "shared prefix, shorter first",
			in:   []string{"10x", "10"},
			want: []string{"10", "10x"},
		},
		{
			name: "equal digit runs break ties on run length",
			in:   []string{"a01", "a1", "a001"},
			want: []string{"a1", "a01", "a001"},
		},
		{
			name: "later digit runs compare numerically",
			in:   []string{"a2b10", "a2b9"},
			want: []string{"a2b9", "a2b10"},
		},
		{
			name: "empty string sorts first among strings",
			in:   []string{"a", "", "_"},
			want: []string{"", "_", "a"},
		},
		{
			name: "numeric tier precedes string tier",
			in:   []string{"10", "alpha", "-1", "2x", "1.5"},
			want: []string{"-1", "1.5", "10", "2x", "alpha"},
		},
		{
			name: "exponent form is numeric-class",
			in:   []string{"1e3", "2000", "100"},
			want: []string{"100", "1e3", "2000"},
		},
		{
			name: "inf and nan lookalikes stay string-class",
			in:   []string{"inf", "+inf", "Infinity", "nan", "NaN", "apple", "5"},
			want: []string{"5", "+inf", "Infinity", "NaN", "apple", "inf", "nan"},
		},
		{
			name: "equal numeric value, int shape before float shape",
			in:   []string{"1.0", "1"},
			want: []string{"1", "1.0"},
		},
		{
			name: "equal numeric value, exponent is float shape",
			in:   []string{"1e3", "1000"},
			want: []string{"1000", "1e3"},
		},
		{
			// residual: spruce orders quoted "1" in the string tier
			// ("_", "1", "a"); graft classifies every numeric-looking
			// coerced key into the numeric tier by design.
			name: "residual quoted-digit key joins the numeric tier",
			in:   []string{"1", "a", "_"},
			want: []string{"1", "_", "a"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := append([]string(nil), tc.in...)
			sort.SliceStable(got, func(i, j int) bool {
				return spruceKeyLess(got[i], got[j])
			})
			if !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("sorted order mismatch\n got: %q\nwant: %q", got, tc.want)
			}
			// The comparator must be strict on every adjacent pair so
			// the emitted order never depends on map iteration order.
			for i := 0; i+1 < len(tc.want); i++ {
				a, b := tc.want[i], tc.want[i+1]
				if !spruceKeyLess(a, b) {
					t.Errorf("spruceKeyLess(%q, %q) = false, want true", a, b)
				}
				if spruceKeyLess(b, a) {
					t.Errorf("spruceKeyLess(%q, %q) = true, want false", b, a)
				}
			}
		})
	}
}

func TestSpruceKeyLessIrreflexive(t *testing.T) {
	for _, k := range []string{"", "a", "1", "1.0", "a01", "int_val", "~t", "inf"} {
		if spruceKeyLess(k, k) {
			t.Errorf("spruceKeyLess(%q, %q) = true, want false", k, k)
		}
	}
}
