package operators

import (
	"fmt"

	"github.com/fivetwenty-io/graft/internal/utils/ansi"
	"github.com/fivetwenty-io/graft/pkg/graft"
	"github.com/fivetwenty-io/graft/pkg/graft/tree"
)

// CartesianProductOperator computes the Cartesian product of two or more lists.
type CartesianProductOperator struct{}

// Setup initializes the operator.
func (CartesianProductOperator) Setup() error {
	return nil
}

// Phase returns which phase this operator should run in.
func (CartesianProductOperator) Phase() OperatorPhase {
	return EvalPhase
}

// Dependencies returns what keys the operator depends on.
func (CartesianProductOperator) Dependencies(ev *Evaluator, args []*Expr, locs []*tree.Cursor, auto []*tree.Cursor) []*tree.Cursor {
	l := []*tree.Cursor{}

	for _, arg := range args {
		switch arg.Type {
		case graft.Reference:
			// arg.Reference is nil for a bare @name token that parsed as an
			// orphaned target rather than a value reference: see
			// operator_helpers.go's ResolveOperatorArgument doc comment on
			// the same condition. It contributes no dependency.
			if arg.Reference == nil {
				continue
			}
			for _, other := range locs {
				if other.Under(arg.Reference) {
					l = append(l, other)
				}
			}
		case graft.OperatorCall:
			// Get dependencies from nested operator, preferring ev's
			// engine-local registry (see evaluateNestedOperator).
			// graft.EngineOf, not graft.GetEngine: see operator_helpers.go.
			nestedOp := OperatorForEngine(graft.EngineOf(ev), arg.Op())
			if _, ok := nestedOp.(graft.NullOperator); !ok {
				nestedDeps := nestedOp.Dependencies(ev, arg.Args(), locs, auto)
				l = append(l, nestedDeps...)
			}
		case graft.Literal, graft.List, graft.Or, graft.Negate, graft.Addition, graft.Subtraction, graft.Multiplication, graft.Division, graft.Modulo,
			graft.Equal, graft.NotEqual, graft.LessThan, graft.LessThanOrEqual, graft.GreaterThan, graft.GreaterThanOrEqual,
			graft.LogicalAnd, graft.LogicalOr, graft.RegexpMatch, graft.EnvVar, graft.BoshVar, graft.VaultGroup, graft.VaultChoice:
			// No dependencies for these types
		}
	}

	// Append autogenerated dependencies (operator reference-type arguments)
	l = append(l, auto...)

	return l
}

// Run executes the cartesian-product operator.
func (CartesianProductOperator) Run(ev *Evaluator, args []*Expr) (*Response, error) {
	DEBUG("running (( cartesian-product ... )) operation at $.%s", ev.Here)
	defer DEBUG("done with (( cartesian-product ... )) operation at $.%s\n", ev.Here)

	if len(args) == 0 {
		DEBUG("  no arguments supplied to (( cartesian-product ... )) operation. oops.")
		return nil, ansi.Errorf("no arguments specified to @c{(( cartesian-product ... ))}")
	}

	var lists [][]interface{}

	for i, arg := range args {
		// Use ResolveOperatorArgument to support nested expressions
		val, err := ResolveOperatorArgument(ev, arg)
		if err != nil {
			DEBUG("     [%d]: resolution failed\n    error: %s", i, err)
			return nil, err
		}

		if val == nil {
			DEBUG("  arg[%d]: resolved to nil", i)
			return nil, fmt.Errorf("cartesian-product operator argument cannot be nil")
		}

		switch v := val.(type) {
		case []interface{}:
			DEBUG("  arg[%d]: found list value with %d elements", i, len(v))
			// Validate that list contains only scalar values
			for j, item := range v {
				if _, isList := item.([]interface{}); isList {
					DEBUG("       list[%d]: list item is itself a list; error!", j)
					return nil, fmt.Errorf("cartesian-product operator can only operate on lists of scalar values")
				}
				if _, isMap := item.(map[string]interface{}); isMap {
					DEBUG("       list[%d]: list item is a map; error!", j)
					return nil, fmt.Errorf("cartesian-product operator can only operate on lists of scalar values")
				}
				DEBUG("       list[%d]: list item is a scalar: %v", j, item)
			}
			lists = append(lists, v)

		case map[string]interface{}:
			DEBUG("     [%d]: resolved to a map; error!", i)
			return nil, fmt.Errorf("cartesian-product operator only accepts arrays and scalar values")

		default:
			// Scalar value becomes a single-element list
			DEBUG("  arg[%d]: found scalar value '%v', wrapping as single-element list", i, val)
			lists = append(lists, []interface{}{val})
		}
		DEBUG("")
	}

	// Handle edge cases
	if len(lists) == 0 {
		DEBUG("  no lists to compute product of, returning empty list")
		return &Response{
			Type:  Replace,
			Value: []interface{}{},
		}, nil
	}

	if len(lists) == 1 {
		DEBUG("  called with only one argument; returning values as strings")
		result := make([]interface{}, len(lists[0]))
		for i, v := range lists[0] {
			result[i] = fmt.Sprintf("%v", v)
		}
		return &Response{
			Type:  Replace,
			Value: result,
		}, nil
	}

	// Check for empty lists - if any list is empty, result is empty
	for _, list := range lists {
		if len(list) == 0 {
			DEBUG("  one of the lists is empty; returning empty result")
			return &Response{
				Type:  Replace,
				Value: []interface{}{},
			}, nil
		}
	}

	DEBUG("  computing cartesian product of %d lists", len(lists))

	// Compute cartesian product iteratively
	result := cartesianProduct(lists)

	return &Response{
		Type:  Replace,
		Value: result,
	}, nil
}

// cartesianProduct computes the Cartesian product of multiple lists
// Returns a list of concatenated strings for each combination.
func cartesianProduct(lists [][]interface{}) []interface{} {
	if len(lists) == 0 {
		return []interface{}{}
	}

	// Start with the first list, each element becomes a string
	result := make([]interface{}, len(lists[0]))
	for i, v := range lists[0] {
		result[i] = fmt.Sprintf("%v", v)
	}

	// Iteratively add each subsequent list
	for _, list := range lists[1:] {
		result = cartesianExtend(result, list)
	}

	return result
}

// cartesianExtend extends existing combinations with elements from a new list
// by concatenating each existing string with each new element.
func cartesianExtend(existing []interface{}, newList []interface{}) []interface{} {
	if len(existing) == 0 || len(newList) == 0 {
		return []interface{}{}
	}

	result := make([]interface{}, 0, len(existing)*len(newList))

	for _, combo := range existing {
		comboStr := fmt.Sprintf("%v", combo)

		for _, elem := range newList {
			// Concatenate the existing string with the new element
			newCombo := comboStr + fmt.Sprintf("%v", elem)
			result = append(result, newCombo)
		}
	}

	return result
}

//nolint:gochecknoinits // Operator registration must happen at package load time
func init() {
	RegisterOp("cartesian-product", CartesianProductOperator{})
	RegisterOp("cartesian", CartesianProductOperator{})
}
